### ISSUE TITLE
Guidance for creating bounded contexts to help create a well structured monolith

### ISSUE THREAD

**Issue by mikegehard** [collinschaafsma/startstack#10]
## Is your feature request related to a problem? Please describe.

Small apps are easy to organize and keep "clean". As an application grows, dependencies become unclear, code becomes spaghetti like and velocity suffers.

## Describe the solution you'd like

Examples of using modules to break the code up into bounded contexts to help guide folks towards a well structure monolith. An example can be found here: https://www.appcontinuum.io/

**Comment by collinschaafsma** [comment]
hi @mikegehard! I have intentionally made this project as simple as possible, but I do have a lot of experience with monolith apps with large codebases. For something small, like startstack, you can read my thoughts here. https://www.startstack.io/docs/project-structure. For larger apps (with teams) I recommend looking at something like https://turbo.build/ to organize your project, modules, packages etc. I've found that "raising" code into packages / apps / context etc. after it becomes painfully obvious you need to rather than out of the gate avoids premature complexity and more accurate boundaries. Let me know what you think! Thanks so much for checking out startstack!
